name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        include:
          # clang build on Debug & Release
          - name: Debug clang
            build_type: Debug
            cc: clang
            cxx: clang++
          - name: Release clang
            build_type: Release
            cc: clang
            cxx: clang++
          # gcc build on Debug & Release
          - name: Debug GCC
            build_type: Debug
            cc: gcc
            cxx: g++
          - name: Release GCC
            build_type: Release
            cc: gcc
            cxx: g++    

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Configure VM
      run: sh ${{github.workspace}}/tools/linux/scripts/trusty-install-deps.sh

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.build_type}} -DCMAKE_CXX_COMPILER=${{env.cxx}} -DCMAKE_C_COMPILER=${{env.cc}} -DCINDER_BUILD_TESTS=1

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.build_type}} --parallel

    - name: Run Tests
      fail-on-error: true
      working-directory: ${{github.workspace}}/build
      run: ${{github.workspace}}/{{$env.build_type}}/UnitTests/UnitTests